<a href="https://colab.research.google.com/github/KarinVe/wotech-python-2024/blob/main/0607_pandas_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data_list = [1,2,3,4,5]
print(data_list)

[1, 2, 3, 4, 5]

###Pandas series

In [3]:
series_from_list = pd.Series(data_list)
print(series_from_list)

0    1
1    2
2    3
3    4
4    5
dtype: int64

###Pandas DataFrame

In [4]:
dataframe_from_list = pd.DataFrame(data_list)
print(dataframe_from_list)

   0
0  1
1  2
2  3
3  4
4  5

###Pandas Series from Dictionary

In [5]:
data_dict = {'A': 10, 'B': 20, 'C': 30, 'D': 40, 'E': 50} #dictionary object key-value pairs, #index is not predefined anymore, we define the index

series_from_dict = pd.Series(data_dict)
print(series_from_dict)

#dtype: int64 - integer values

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [6]:
csv_data = "1,2,3,4,5" #string
csv_data.split(',') #sprit the string into a list

['1', '2', '3', '4', '5']

In [7]:
series_from_list_split = pd.Series(csv_data.split(','))
print(series_from_list_split)

0    1
1    2
2    3
3    4
4    5
dtype: object

###DataFrames

In [8]:
data_list = [
    ['John', 30, 68.5, True, 95.5],
    ['Alice', 25, 63.2, False, 88.0],
    ['Bob', 35, 71.0, True, 76.5],
    ['Eve', 28, 65.8, False, 92.0],
    ['Charlie', 40, 72.3, False, 87.5]
]

pd.DataFrame(data_list)

         0   1     2      3     4
0     John  30  68.5   True  95.5
1    Alice  25  63.2  False  88.0
2      Bob  35  71.0   True  76.5
3      Eve  28  65.8  False  92.0
4  Charlie  40  72.3  False  87.5

In [9]:
data_list = [
    ['John', 30, 68.5, True, 95.5],
    ['Alice', 25, 63.2, False, 88.0],
    ['Bob', 35, 71.0, True, 76.5],
    ['Eve', 28, 65.8, False, 92.0],
    ['Charlie', 40, 72.3, False, 87.5]
]

column_names = ['Name', 'Age', 'Weight', 'Is Student', 'Score'] #we define column names
pd.DataFrame(data_list, columns=column_names)

      Name  Age  Weight  Is Student  Score
0     John   30    68.5        True   95.5
1    Alice   25    63.2       False   88.0
2      Bob   35    71.0        True   76.5
3      Eve   28    65.8       False   92.0
4  Charlie   40    72.3       False   87.5

###Working with a CSV file

In [10]:
df = pd.read_csv('/content/transaction_dataset.csv') #method to read csv-file #we need to specify, where is the file located #we have read in the file

In [11]:
df.head() #this method gives first 5 rows of dataframe

,Customer ID,Name,Surname,Gender,Birthdate,Transaction Amount,Date,Merchant Name,Category
0,752858,Sean,Rodriguez,F,20/10/2002,35.47,03/04/2023,Smith-Russell,Cosmetic
1,26381,Michelle,Phelps,NaN,24/10/1985,2552.72,17/07/2023,"Peck, Spence and Young",Travel
2,305449,Jacob,Williams,M,25/10/1981,115.97,20/09/2023,Steele Inc,Clothing
3,988259,Nathan,Snyder,M,26/10/1977,11.31,11/01/2023,"Wilson, Wilson and Russell",Cosmetic
4,764762,Crystal,Knapp,F,02/11/1951,62.21,13/06/2023,Palmer-Hinton,Electronics

In [12]:
df.tail() #this method gives last 5 rows of dataframe

,Customer ID,Name,Surname,Gender,Birthdate,Transaction Amount,Date,Merchant Name,Category
49995,891845,Christine,Leach,F,21/10/1997,108.74,30/08/2023,Alexander Ltd,Market
49996,800560,Anna,Allen,F,21/10/1999,133.66,03/05/2023,Knapp-Calhoun,Cosmetic
49997,133285,Nicole,Franklin,M,26/10/1979,464.29,12/02/2023,"Cantrell, Haynes and Ballard",Market
49998,616122,Maria,Keller,M,25/10/1981,472.57,25/03/2023,"Wilson, Jackson and Beard",Market
49999,832184,Billy,Walker,F,31/10/1958,270.67,20/05/2023,Combs LLC,Market

In [13]:
df.tail(n=10) #you can define, how many rows you want to see

,Customer ID,Name,Surname,Gender,Birthdate,Transaction Amount,Date,Merchant Name,Category
49990,49041,Jasmine,Bradford,NaN,31/10/1958,66.25,01/03/2023,Perez Ltd,Restaurant
49991,145728,Mark,Graham,F,19/10/2004,89.74,17/05/2023,Ingram Inc,Restaurant
49992,528903,Susan,Castaneda,F,01/11/1954,19.01,18/09/2023,"Gonzalez, Jennings and Powers",Market
49993,754013,Katherine,Avery,F,30/10/1961,60.50,16/08/2023,"Wallace, Kim and Rosales",Restaurant
49994,197066,George,Cooper,F,21/10/1998,278.78,29/05/2023,Kim and Sons,Market
49995,891845,Christine,Leach,F,21/10/1997,108.74,30/08/2023,Alexander Ltd,Market
49996,800560,Anna,Allen,F,21/10/1999,133.66,03/05/2023,Knapp-Calhoun,Cosmetic
49997,133285,Nicole,Franklin,M,26/10/1979,464.29,12/02/2023,"Cantrell, Haynes and Ballard",Market
49998,616122,Maria,Keller,M,25/10/1981,472.57,25/03/2023,"Wilson, Jackson and Beard",Market
49999,832184,Billy,Walker,F,31/10/1958,270.67,20/05/2023,Combs LLC,Market

In [14]:
df.shape #this method gives the number of rows and columns

(50000, 9)

In [15]:
df.sample(5) #this method gives random rows

,Customer ID,Name,Surname,Gender,Birthdate,Transaction Amount,Date,Merchant Name,Category
25091,927874,Jesse,Cline,F,28/10/1970,109.69,04/02/2023,Brady Inc,Clothing
44010,32391,Stacy,Johnson,M,22/10/1993,89.02,25/09/2023,Simmons Ltd,Cosmetic
46969,502317,Dean,Elliott,M,25/10/1981,244.52,25/03/2023,Miller-Smith,Clothing
37383,858247,Justin,Andrews,F,21/10/1999,103.26,17/06/2023,"Wood, Flores and Murphy",Market
37587,701366,Dustin,Smith,M,27/10/1973,217.62,16/01/2023,"Brown, Moyer and Hernandez",Clothing

In [16]:
df.info() #this method gives information about the column names, data types (Dtype), how many values NaN (not a number)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer ID         50000 non-null  int64
 1   Name                50000 non-null  object
 2   Surname             50000 non-null  object
 3   Gender              44953 non-null  object
 4   Birthdate           50000 non-null  object
 5   Transaction Amount  50000 non-null  float64
 6   Date                50000 non-null  object
 7   Merchant Name       50000 non-null  object
 8   Category            50000 non-null  object
dtypes: float64(1), int64(1), object(7)
memory usage: 3.4+ MB

In [17]:
df.describe() #this method gives you summary of the statistics of integers or floats

        Customer ID  Transaction Amount
count   50000.00000        50000.000000
mean   500136.79696          442.119239
std    288232.43164          631.669724
min        29.00000            5.010000
25%    251191.50000           79.007500
50%    499520.50000          182.195000
75%    749854.25000          470.515000
max    999997.00000         2999.880000

In [18]:
df.describe(include='object') #this method gives you summary statistics of strings

,Name,Surname,Gender,Birthdate,Date,Merchant Name,Category
count,50000,50000,44953,50000,50000,50000,50000
unique,690,1000,2,58,287,36939,6
top,Michael,Smith,F,01/11/1954,30/06/2023,Smith Ltd,Restaurant
freq,1167,1095,22713,914,200,69,8413

In [19]:
df.head() #to see column names

,Customer ID,Name,Surname,Gender,Birthdate,Transaction Amount,Date,Merchant Name,Category
0,752858,Sean,Rodriguez,F,20/10/2002,35.47,03/04/2023,Smith-Russell,Cosmetic
1,26381,Michelle,Phelps,NaN,24/10/1985,2552.72,17/07/2023,"Peck, Spence and Young",Travel
2,305449,Jacob,Williams,M,25/10/1981,115.97,20/09/2023,Steele Inc,Clothing
3,988259,Nathan,Snyder,M,26/10/1977,11.31,11/01/2023,"Wilson, Wilson and Russell",Cosmetic
4,764762,Crystal,Knapp,F,02/11/1951,62.21,13/06/2023,Palmer-Hinton,Electronics

In [21]:
# How do select 1 column in a DataFrame?
df['Gender']

0          F
1        NaN
2          M
3          M
4          F
        ...
49995      F
49996      F
49997      M
49998      M
49999      F
Name: Gender, Length: 50000, dtype: object

In [22]:
# How do select 1 column in a DataFrame?
df['Gender']

# How many unique values?

df['Gender'].unique()

array(['F', nan, 'M'], dtype=object)

In [24]:
df['Gender'] # we access column by a name, we can access several columns

df.Gender # we access the same column

0          F
1        NaN
2          M
3          M
4          F
        ...
49995      F
49996      F
49997      M
49998      M
49999      F
Name: Gender, Length: 50000, dtype: object

In [23]:
df['Merchant Name'] # we access column by a name, we can access several columns

df.Merchant Name # accessing column with an attribute # see variant ei sobi, sest column name sisaldab tühikut

SyntaxError: invalid syntax (<ipython-input-23-6b81036de44f>, line 3)

In [25]:
df['Gender'] # we access column by a name, we can access several columns

df.Gender # accessing column with an attribute

df.iloc[:, 3] # accessing column with index, iloc - index location [row, column], you can have several rows and columns here, similar to list indexing

0          F
1        NaN
2          M
3          M
4          F
        ...
49995      F
49996      F
49997      M
49998      M
49999      F
Name: Gender, Length: 50000, dtype: object

In [27]:
# value counts

df['Gender'].value_counts(dropna = False) # I do not want to drop empty values here

Gender
F      22713
M      22240
NaN     5047
Name: count, dtype: int64

In [33]:
df.isna() # whether value is empty, binary False = 0, True = 1

,Customer ID,Name,Surname,Gender,Birthdate,Transaction Amount,Date,Merchant Name,Category
0,False,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
49995,False,False,False,False,False,False,False,False,False
49996,False,False,False,False,False,False,False,False,False
49997,False,False,False,False,False,False,False,False,False
49998,False,False,False,False,False,False,False,False,False
49999,False,False,False,False,False,False,False,False,False

In [34]:
df.isna().sum() # how many empty values

Customer ID              0
Name                     0
Surname                  0
Gender                5047
Birthdate                0
Transaction Amount       0
Date                     0
Merchant Name            0
Category                 0
dtype: int64

In [31]:
df.notna().sum() # how many not empty values

Customer ID           50000
Name                  50000
Surname               50000
Gender                44953
Birthdate             50000
Transaction Amount    50000
Date                  50000
Merchant Name         50000
Category              50000
dtype: int64

In [32]:
df.notna().all() # it checks if all values are not empty

Customer ID            True
Name                   True
Surname                True
Gender                False
Birthdate              True
Transaction Amount     True
Date                   True
Merchant Name          True
Category               True
dtype: bool

In [35]:
# Drop empty values

df.dropna() # drop rows with empty values, it does not override existing values

,Customer ID,Name,Surname,Gender,Birthdate,Transaction Amount,Date,Merchant Name,Category
0,752858,Sean,Rodriguez,F,20/10/2002,35.47,03/04/2023,Smith-Russell,Cosmetic
2,305449,Jacob,Williams,M,25/10/1981,115.97,20/09/2023,Steele Inc,Clothing
3,988259,Nathan,Snyder,M,26/10/1977,11.31,11/01/2023,"Wilson, Wilson and Russell",Cosmetic
4,764762,Crystal,Knapp,F,02/11/1951,62.21,13/06/2023,Palmer-Hinton,Electronics
5,576539,Monica,Bartlett,F,20/10/2001,99.14,24/08/2023,"Tran, Torres and Joyce",Cosmetic
...,...,...,...,...,...,...,...,...,...
49995,891845,Christine,Leach,F,21/10/1997,108.74,30/08/2023,Alexander Ltd,Market
49996,800560,Anna,Allen,F,21/10/1999,133.66,03/05/2023,Knapp-Calhoun,Cosmetic
49997,133285,Nicole,Franklin,M,26/10/1979,464.29,12/02/2023,"Cantrell, Haynes and Ballard",Market
49998,616122,Maria,Keller,M,25/10/1981,472.57,25/03/2023,"Wilson, Jackson and Beard",Market
49999,832184,Billy,Walker,F,31/10/1958,270.67,20/05/2023,Combs LLC,Market

In [42]:
df_new_dataframe = df.dropna() #save it in new df
df.dropna(inplace=True) # drop rows with empty values, specify that you want to override existing dataframe

In [43]:
df

,Customer ID,Name,Surname,Gender,Birthdate,Transaction Amount,Date,Merchant Name,Category
0,752858,Sean,Rodriguez,F,20/10/2002,35.47,03/04/2023,Smith-Russell,Cosmetic
2,305449,Jacob,Williams,M,25/10/1981,115.97,20/09/2023,Steele Inc,Clothing
3,988259,Nathan,Snyder,M,26/10/1977,11.31,11/01/2023,"Wilson, Wilson and Russell",Cosmetic
4,764762,Crystal,Knapp,F,02/11/1951,62.21,13/06/2023,Palmer-Hinton,Electronics
5,576539,Monica,Bartlett,F,20/10/2001,99.14,24/08/2023,"Tran, Torres and Joyce",Cosmetic
...,...,...,...,...,...,...,...,...,...
49995,891845,Christine,Leach,F,21/10/1997,108.74,30/08/2023,Alexander Ltd,Market
49996,800560,Anna,Allen,F,21/10/1999,133.66,03/05/2023,Knapp-Calhoun,Cosmetic
49997,133285,Nicole,Franklin,M,26/10/1979,464.29,12/02/2023,"Cantrell, Haynes and Ballard",Market
49998,616122,Maria,Keller,M,25/10/1981,472.57,25/03/2023,"Wilson, Jackson and Beard",Market
49999,832184,Billy,Walker,F,31/10/1958,270.67,20/05/2023,Combs LLC,Market

In [44]:
# Saving the cleaned file

df.to_csv('cleaned_data.csv') #the file will be saved in the current working directory, it can be saved in the different directory as well